using System;
using System.Collections.Generic;

namespace AntConfigurer.Objects
{
    class ConfigElement
    {
        private String _url;
        private String _pass;
        private String _username;
        private String _worker;
        private String _asicIp;
        private String _prefix;
        private String _suffix;
        private Int32 _ctr;
        
        private List<String> _errors = new List<string>();

        public String GetUrl()
        {
            return this._url;
        }

        public ConfigElement SetUrl(String url)
        {
            this._url = url;
            return this;
        }

        public String GetWorker()
        {
            return this._worker;
        }

        public ConfigElement SetWorker(String worker)
        {
            this._worker = worker;
            return this;
        }

        public String GetPass()
        {
            return this._pass;
        }

        public ConfigElement SetPass(String pass)
        {
            this._pass = pass;
            return this;
        }

        public String GetAsicIp()
        {
            return this._asicIp;
        }

        public ConfigElement SetAsicIp(String asicIp)
        {
            this._asicIp = asicIp;
            return this;
        }

        public String GetUsername()
        {
            return this._username;
        }

        public ConfigElement SetUsername(String username)
        {
            this._username = username;
            return this;
        }

        public String GetPrefix()
        {
            return this._prefix;
        }

        public ConfigElement SetPrefix(String prefix)
        {
            this._prefix = prefix;
            return this;
        }

        public String GetSuffix()
        {
            return this._suffix;
        }

        public ConfigElement SetSuffix(String suffix)
        {
            this._suffix = suffix;
            return this;
        }


        public Int32 GetCtr()
        {
            return this._ctr;
        }

        public ConfigElement SetCtr(Int32 ctr)
        {
            this._ctr = ctr;
            return this;
        }

        public List<String> GetErrors()
        {
            return this._errors;
        }

        public Boolean Check(Boolean autoSetWorkername = true, Boolean bypassAutoset = false)
        {
            List<String> errors = new List<string>();
            
            if (String.IsNullOrWhiteSpace(this._url))
            {
                errors.Add("ASIC's #" + this._ctr + " url is empty");
            }

            /*
            if (String.IsNullOrWhiteSpace(this.username))
            {
                _errors.Add("Please, provide for ASIC #" + this.ctr);
                auto_set_workername = false;
            }
            */

            if (String.IsNullOrWhiteSpace(this._worker))
            {
                if (true || !autoSetWorkername)
                {
                    errors.Add("ASIC's #" + this._ctr + " worker is empty");
                }
                else if (!bypassAutoset)
                {
                    // For autosetting worker's name we assume that passed IP is correct
                    String[] octets = this._asicIp.Split('.');
                    
                    if (octets.Length < 2)
                    {
                        errors.Add("Couldn't autoset worker name for ASIC# " + this._ctr + ". IP address is: " + this._asicIp);
                    }
                    else
                    {
                        String fourthOctet = octets[octets.Length - 1],
                               thirdOctet = octets[octets.Length - 2];

                        String autoGeneratedWName = this._username + "." + Strings.ZeroFill(thirdOctet) + Strings.ZeroFill(fourthOctet);
                        this._worker = autoGeneratedWName;
                    }
                }
            }

            this._errors = errors;
            return this._errors.Count < 1;
        }

        public Boolean GenerateWorkerName(String ipAddress, String macAddress = "")
        {
            if (String.IsNullOrWhiteSpace(ipAddress))
            {
                return false;
            }

            String[] octets = ipAddress.Split('.');
            
            if (octets.Length < 2)
            {
                return false;
            }

            String fourthOctet = octets[octets.Length - 1], thirdOctet = octets[octets.Length - 2];

            // String auto_generated_w_name = this.username + "." + Strings.zeroFill(third_octet) + Strings.zeroFill(fourth_octet);
            String autoGeneratedWName = this._username;
            
            if (!String.IsNullOrWhiteSpace(this._prefix))
            {
                autoGeneratedWName = this._prefix + autoGeneratedWName;
            }

            if (!String.IsNullOrWhiteSpace(this._suffix))
            {
                autoGeneratedWName += this._suffix;
            }

            if (!String.IsNullOrWhiteSpace(macAddress))
            {
                String clearedMac = macAddress.Replace(":", String.Empty).TrimEnd('\r', '\n');
                clearedMac = clearedMac.Substring(0, Math.Min(5, clearedMac.Length));
                autoGeneratedWName += ("x" + clearedMac);
            }

            this._worker = autoGeneratedWName;
            return true;
        }
    }
}
